version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production  # Corrected indentation
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: node index.js
